// Load Scala.js config generated by sbt
fetch('/scalajs-config.json')
  .then(res => res.json())
  .then(config => {
    const scriptPath = import.meta.env.MODE === 'production'
      ? config.fullOptPath
      : config.fastOptPath;

    return import(scriptPath);
  })
  .then(() => {
    // Initialize the ScalaJS app
    if (typeof Main !== 'undefined' && Main.main) {
      Main.main();
    }
  })
  .catch(err => {
    console.error('Failed to load Scala.js application:', err);
    console.error('Make sure to run sbt compile first to generate the config');
  });
