// Load Scala.js config generated by sbt
fetch('/scalajs-config.json')
  .then(res => res.json())
  .then(config => {
    const script = document.createElement('script');
    script.type = 'module';
    script.src = import.meta.env.MODE === 'production'
      ? config.fullOptPath
      : config.fastOptPath;
    document.body.appendChild(script);
  })
  .catch(err => {
    console.error('Failed to load scalajs-config.json:', err);
    console.error('Make sure to run sbt compile first to generate the config');
  });
